# Generated by Django 5.0.4 on 2024-05-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_address_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
