fail_fast: true
exclude: "/migrations/"

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.4.5
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format

    - repo: local
      hooks:
        - id: check-django-migrations
          name: Check Django migrations
          entry: python manage.py makemigrations --check --settings=config.settings.local
          language: system
          types: [ python ]
          pass_filenames: false
