services:
    - type: web
      plan: free
      name: capricci-backend
      runtime: python
      buildCommand: "./build.sh"
      startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
      envVars:
          - key: WEB_CONCURRENCY
            value: 4
