services:
    - type: web
      plan: free
      name: capricci-backend
      runtime: python
      buildCommand: "./build.sh"
      startCommand: "python -m uvicorn config.wsgi:application --host 0.0.0.0"
      envVars:
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
