# Generated by Django 5.0.4 on 2024-04-22 20:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("items_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_status", models.CharField(max_length=50)),
                ("shipping_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=50)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customer.customer")),
                (
                    "shipping_address",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customer.address"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="order.order")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.product")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
