# Generated by Django 5.0.4 on 2024-04-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address",
            new_name="address",
        ),
    ]
