# Generated by Django 5.0.4 on 2024-04-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
