# Generated by Django 5.0.4 on 2024-04-23 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Password must have more than 8 characters, symbols, numbers, uppercase and lowercase', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\\$%\\^&\\*])(?=.{8,})')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
