# Generated by Django 5.0.4 on 2024-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_password_alter_customer_points'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
