# Generated by Django 5.0.4 on 2024-05-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
